services:
  restapibackend:
    image: restapibackend
    build:
      context: .
      dockerfile: RestApiBackend/Dockerfile

  backend.html:
    image: backend.html
    build:
      context: .
      dockerfile: Backend.Html/Dockerfile
