services:
#  backend.restapi:
#    image: ghcr.io/pogex/flashiercards-backend.restapi:develop
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#      - "8081:8081"
#    environment:
#      ASPNETCORE_ENVIRONMENT: "Development"
#    networks:
#      - "frontend"
#      - "database"
#    volumes:
#      - rest-backend-data-store:/flashiercards/data
#      - rest-backend-config:/flashiercards/config
#    depends_on:
#      - db

#  backend.html:
#    image: ghcr.io/pogex/flashiercards-backend.html:develop
#    restart: unless-stopped
#    ports:
#      - "8082:8080"
#      - "8083:8081"
#    environment:
#      ASPNETCORE_ENVIRONMENT: "Development"
#    networks:
#      - "frontend"
#    volumes:
#      - html-backend-config:/flashiercards/config
#    depends_on:
#      - backend.restapi
  backend:
    image: ghcr.io/pogex/flashiercards-backend.restart:develop
    restart: unless-stopped
    ports:
        - "8080:8080"
        - "8081:8081"
    environment:
        ASPNETCORE_ENVIRONMENT: "Release"
    volumes:
      - backend-config:/flashiercards/config
    depends_on:
      - db
    
  db:
    image: mysql:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: flashiercards
    ports:
      - "8079:3306"
      - "22222:22"
    volumes:
      - db-data:/etc/data
      - db-config:/var/lib/mysql
  
volumes:
  db-data:
  db-config:
#  rest-backend-data-store:
  backend-config:
#  html-backend-config:
  
