services:
  restapibackend:
    image: ghcr.io/pogex/flashiercards:develop-rest
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - "frontend"
      - "database"
    volumes:
      - backend-data-store:/app/data

  backend.html:
    image: ghcr.io/pogex/flashiercards:develop-html
    ports:
      - "8082:8080"
      - "8083:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - "frontend"
    
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: flashiercards
    networks:
      - "database"
    volumes:
      - db-data:/etc/data
  
networks:
  frontend: {}
  database: {}
  
volumes:
  db-data:
  backend-data-store:
  
