services:
  backend.restapi:
    image: ghcr.io/pogex/flashiercards-backend.restapi:develop
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - "frontend"
      - "database"
    volumes:
      - backend-data-store:/app/data
    depends_on:
      - db

  backend.html:
    image: ghcr.io/pogex/flashiercards-backend.html:develop
    ports:
      - "8082:8080"
      - "8083:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - "frontend"
    depends_on:
      - backend.restapi
    
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: flashiercards
    ports:
      - "8079:3306"
    networks:
      - "database"
    volumes:
      - db-data:/etc/data
      - db-config:/var/lib/mysql
  
networks:
  frontend: {}
  database: {}
  
volumes:
  db-data:
  db-config:
  backend-data-store:
  
