services:
  backend:
    image: ghcr.io/pogex/flashiercards-backend.restart:main
    restart: unless-stopped
    ports:
        - "8080:8080"
        - "8081:8081"
    environment:
        ASPNETCORE_ENVIRONMENT: "Release"
    volumes:
      - backend-config:/flashiercards/config
    depends_on:
      - db
    networks:
      - flashiercards
    
  db:
    image: mysql:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: flashiercards
    ports:
      - "3306:3306"
      - "2222:22"
    volumes:
      - db-data:/etc/data
      - db-config:/var/lib/mysql
    networks:
      - flashiercards
              
networks:
  flashiercards:
  
volumes:
  db-data:
  db-config:
  backend-config:

  
