name: Publish RestApi docker container
on:
  workflow_run:
    workflows: [".Net Build"]
    branches: [ "main", "develop"]
    types:
      - completed

env:
  GIT_REGISTRY: ghcr.io
  PRIVATE_REGISTRY: dockerreg.descus.de
  IMAGE_NAME: ${{github.repository}}

jobs:
  build-and-push-rest:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.GIT_REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          
      - name: Login to descus.de
        uses: docker/login-action@v3
        with:
          registry: ${{env.PRIVATE_REGISTRY}}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Backend.RestApi/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}-rest
          labels: ${{ steps.meta.outputs.labels }}
          
  build-and-push-html:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Backend.Html/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}-html
          labels: ${{ steps.meta.outputs.labels }}