name: Publish RestApi docker container
on:
  workflow_run:
    workflows: [".Net Build"]
    branches: [ "main", "develop"]
    types:
      - completed

env:
  GIT_REGISTRY: ghcr.io
  PRIVATE_REGISTRY: dockerreg.descus.de
  IMAGE_NAME: ${{github.repository}}

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.GIT_REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          
      - name: Login to descus.de
        uses: docker/login-action@v3
        with:
          registry: ${{env.PRIVATE_REGISTRY}}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.IMAGE_NAME }}"
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Backend.RestApi/Dockerfile
          push: true
          tags: 
            - "${{GIT_REGISTRY}}/${{github.ref_name}}"
            - "${{PRIVATE_REGISTRY}}/${{github.ref_name}}"
          labels: ${{ steps.meta.outputs.labels }}